package com.mdviewer.service;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

/**
 * The name a diagram is filed under, which two programs have to agree on.
 *
 * <p>This machine uploads the picture under the key; a browser that has never seen the
 * picture asks for it by computing the same key from the same fence. There is no handshake
 * and no negotiation - if the two rules ever differ, every diagram in the browser silently
 * shows its source instead, and nothing anywhere reports a fault. So the rule is asserted
 * here against a value neither implementation produced.
 */
class DiagramKeyTest {

    /**
     * The published SHA-256 of "abc". Chosen over a hash of a real diagram precisely because
     * it comes from outside both implementations: a fixture generated by running this code
     * would agree with itself no matter what it did.
     */
    private static final String SHA256_OF_ABC =
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad";

    @Test
    @DisplayName("the key is the SHA-256 of the source, in lower-case hex")
    void hashesTheSource() {
        assertEquals(SHA256_OF_ABC, DiagramKey.of("abc"));
    }

    /**
     * A document written on Windows carries CRLF; the same document synced to a browser is
     * read as text and may not. Without this the two ends would file the same diagram under
     * two names, and every Windows-authored diagram would show its source in the browser.
     */
    @Test
    @DisplayName("line endings and surrounding blank space do not change the name")
    void normalises() {
        assertEquals(SHA256_OF_ABC, DiagramKey.of("abc\n"));
        assertEquals(SHA256_OF_ABC, DiagramKey.of("\n  abc  \n\n"));
        assertEquals(SHA256_OF_ABC, DiagramKey.of("abc\r\n"));
        assertEquals(SHA256_OF_ABC, DiagramKey.of("\r\nabc\r\n"));
    }

    /**
     * Inner line endings are left alone. Normalising them too would be defensible, but the
     * web side would have to do exactly the same thing to the same bytes, and every rule
     * added here is a rule that can drift over there.
     */
    @Test
    @DisplayName("a different diagram is a different name")
    void distinguishes() {
        assertNotEquals(DiagramKey.of("@startuml\nAlice -> Bob\n@enduml"),
                DiagramKey.of("@startuml\nAlice -> Carol\n@enduml"));
    }

    /**
     * The raw fence, not what the renderer makes of it.
     *
     * <p>{@link DiagramService#prepare} rewrites C4 includes and inserts a layout pragma -
     * Java the browser does not have. Hashing its output would give this machine a name the
     * browser could never compute, and every diagram would look unrendered.
     */
    @Test
    @DisplayName("the key comes from the fence, not from what the renderer does with it")
    void hashesWhatTheBrowserCanSee() {
        String fence = "Alice -> Bob";
        assertNotEquals(DiagramKey.of(DiagramService.prepare(fence)), DiagramKey.of(fence));
    }

    @Test
    @DisplayName("nothing at all still has a name")
    void empty() {
        assertEquals(64, DiagramKey.of("").length());
        assertEquals(DiagramKey.of(""), DiagramKey.of("   \r\n  "));
    }
}
